apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-remote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbl-weather-station-remote
  template:
    metadata:
      labels:
        app: lbl-weather-station-remote
    spec:
      containers:
        - name: meto-station
          image: meto-station:latest
          imagePullPolicy: Never
          env:
            - name: bootstrap.servers
              value: kafka-service:9092
            - name: TOPIC
              value: station
            - name: Dropped
              value: droppedmessage
            - name: STATION_ID
              value: "11"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-remote
spec:
  selector:
    app: lbl-weather-station-remote
  ports:
    - name: weather-station-remote
      port: 8080
      targetPort: 8080
